CREATE TABLE team_seasonal_receiving_rushing_metrics (
    team_id INT,
    season INT,
	--rushing
	rush_att INT,
	rush_yds_per_att FLOAT,
	rush_fd INT,
	rush_success FLOAT,
	rush_long INT,
	rush_yds_per_g FLOAT,
	rush_att_per_g FLOAT,
	rush_yds INT,
	rush_tds INT,
	--receiving
    targets INT,
    rec INT,
    rec_yds INT,
    rec_yds_per_rec FLOAT,
    rec_td INT,
    rec_first_down INT,
    rec_success FLOAT,
    rec_long INT,
    rec_per_g FLOAT,
    rec_yds_per_g FLOAT,
    catch_pct FLOAT,
    rec_yds_per_tgt FLOAT,
	--touches
	touches INT,
    yds_per_touch FLOAT,
    yds_from_scrimmage FLOAT,
    rush_receive_td INT,
    fumbles INT,
    PRIMARY KEY (team_id, season),
    FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE
);