CREATE TABLE team_seasonal_defensive_metrics (
    team_id INT,
	season INT,
    points INT,
    total_yards INT,
    plays_offense INT,
    yds_per_play_offense FLOAT,
    turnovers INT,
    fumbles_lost INT,
    first_down INT,
    pass_cmp INT,
    pass_att INT,
    pass_yds INT,
    pass_td INT,
    pass_int INT,
    pass_net_yds_per_att FLOAT,
    pass_fd INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_per_att FLOAT,
    rush_fd INT,
    penalties INT,
    penalties_yds INT,
    pen_fd INT,
    drives INT,
    score_pct FLOAT,
    turnover_pct FLOAT,
    start_avg FLOAT,  -- Converted from string to numeric
    time_avg FLOAT,
    plays_per_drive FLOAT,
    yds_per_drive FLOAT,
    points_avg FLOAT,
    third_down_att INT,
    third_down_success INT,
    third_down_pct FLOAT,
    fourth_down_att INT,
    fourth_down_success INT,
    fourth_down_pct FLOAT,
    red_zone_att INT,
    red_zone_scores INT,
    red_zone_pct FLOAT,
	PRIMARY KEY (team_id, season),
	FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE
);
