-- Store weekly aggregate metrics for a player at a specific point in a season 
CREATE TABLE player_weekly_agg_metrics (
	player_id INT NOT NULL, 
	week INT NOT NULL, 
	season INT NOT NULL, 

	-- Player Advanced Passing Metrics
	avg_pass_first_downs FLOAT,
	avg_pass_first_downs_per_pass_play FLOAT,
	avg_intended_air_yards FLOAT,
	avg_intended_air_yards_per_pass_attempt FLOAT,
	avg_completed_air_yards FLOAT,
	avg_completed_air_yards_per_cmp FLOAT,
	avg_completed_air_yards_per_att FLOAT,
	avg_pass_yds_after_catch FLOAT,
	avg_pass_yds_after_catch_per_cmp FLOAT,
	avg_pass_drops FLOAT,
	avg_pass_drop_pct FLOAT,
	avg_pass_poor_throws FLOAT,
	avg_pass_poor_throws_pct FLOAT,
	avg_pass_blitzed FLOAT,
	avg_pass_hurried FLOAT,
	avg_pass_hits FLOAT,
	avg_pass_pressured FLOAT,
	avg_pass_pressured_pct FLOAT,
	avg_pass_scrambles FLOAT,
	avg_pass_yds_per_scramble FLOAT,

	-- Player Advanced Rushing/Receiving Metrics
	avg_rush_first_downs FLOAT,
	avg_rush_yds_before_contact FLOAT,
	avg_rush_yds_before_contact_per_att FLOAT,
	avg_rush_yds_after_contact FLOAT,
	avg_rush_yds_after_contact_per_att FLOAT,
	avg_rush_broken_tackles FLOAT,
	avg_rush_att_per_broken_tackle FLOAT,
	avg_rec_first_downs FLOAT,
	avg_rec_yds_before_catch FLOAT,
	avg_rec_yds_before_catch_per_rec FLOAT,
	avg_rec_yds_after_catch FLOAT,
	avg_rec_yds_after_catch_per_rec FLOAT,
	avg_avg_depth_of_target FLOAT,
	avg_rec_broken_tackles FLOAT,
	avg_rec_per_broken_tackle FLOAT,
	avg_rec_dropped_passes FLOAT,
	avg_rec_drop_pct FLOAT,
	avg_rec_int_when_targeted FLOAT,
	avg_rec_qbr_when_targeted FLOAT,

	-- Player Game Log Metrics
	avg_completions FLOAT,
	avg_attempts FLOAT,
	avg_pass_yds FLOAT,
	avg_pass_tds FLOAT,
	avg_interceptions FLOAT,
	avg_rating FLOAT,
	avg_sacked FLOAT,
	avg_rush_attempts FLOAT,
	avg_rush_yds FLOAT,
	avg_rush_tds FLOAT,
	avg_targets FLOAT,
	avg_receptions FLOAT,
	avg_rec_yds FLOAT,
	avg_rec_tds FLOAT,
	avg_snap_pct FLOAT,
	avg_offensive_snaps FLOAT,
	avg_fantasy_points FLOAT,

	PRIMARY KEY (player_id, week, season),
	FOREIGN KEY (player_id) REFERENCES player(player_id) ON DELETE CASCADE
);
