CREATE TABLE team_seasonal_passing_metrics (
    team_id INT NOT NULL, 
    season INT NOT NULL,
    pass_attempts INT, 
    complete_pass INT, 
    incomplete_pass INT,
    passing_yards INT, 
    pass_td INT, 
    interception INT, 
    net_yds_per_att FLOAT,
    first_downs INT,
    cmp_pct FLOAT,
    td_pct FLOAT,
    int_pct FLOAT,
    success INT,
    long INT,
    yds_per_att FLOAT,
    adj_yds_per_att FLOAT,
    yds_per_cmp FLOAT,
    yds_per_g FLOAT,
    rating FLOAT,
    sacked INT,
    sacked_yds INT,
    sacked_pct FLOAT,
    adj_net_yds_per_att FLOAT,
    comebacks INT,
    game_winning_drives INT,
    PRIMARY KEY (team_id, season),
    FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE
);
