--- Store generic totals for a team in a given season
CREATE TABLE team_seasonal_general_metircs(
	team_id INT NOT NULL, 
	season INT NOT NULL,
	total_snaps INT,
	total_yards_gained INT,
	total_touchdowns INT, 
	extra_point_attempts iNT,
	field_goal_attempts INT,
	points INT, 
	td_points INT, 
	xp_points INT,
	fg_points INT, 
	fumble INT,
	fumble_lost INT, 
	shotgun_snaps INT, 
	no_huddle_snaps INT, 
	home_wins INT,
	home_losses INT,
	home_ties INT,
	away_wins INT,
	away_losses INT,
	away_ties INT,
	wins INT,
	losses INT,
	tie INT,
	win_pct FLOAT,
	yards_per_snap FLOAT,
	PRIMARY KEY (team_id, season),
	FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE
)
