CREATE TABLE player_seasonal_passing_metrics (
    player_id INT,
    team_id INT,
    season INT,
    games_started INT,
    qb_rec VARCHAR(255),
    pass_att INT,
    pass_cmp_pct FLOAT,
    pass_yds INT,
    pass_td INT,
    pass_td_pct FLOAT,
    pass_int INT,
    pass_int_pct FLOAT,
    pass_first_down INT,
    pass_success FLOAT,
    pass_long INT,
    pass_yds_per_att FLOAT,
    pass_adj_yds_per_att FLOAT,
    pass_yds_per_cmp FLOAT,
    pass_yds_per_g FLOAT,
    pass_rating FLOAT,
    qbr FLOAT,
    pass_sacked INT,
    pass_sacked_yds INT,
    pass_sacked_pct FLOAT,
    pass_net_yds_per_att FLOAT,
    pass_adj_net_yds_per_att FLOAT,
    comebacks INT,
    game_winning_drives INT,
    PRIMARY KEY (player_id, season, team_id),
    FOREIGN KEY (player_id) REFERENCES player(player_id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE
);