CREATE TABLE player_advanced_passing (
    player_id INT NOT NULL,
    week INT NOT NULL,
    season INT NOT NULL,
    age FLOAT NOT NULL,
    first_downs INT,
    first_down_passing_per_pass_play FLOAT,
    intended_air_yards FLOAT,
    intended_air_yards_per_pass_attempt FLOAT,
    completed_air_yards FLOAT,
    completed_air_yards_per_cmp FLOAT,
    completed_air_yards_per_att FLOAT,
    yds_after_catch FLOAT,
    yds_after_catch_per_cmp FLOAT,
    drops INT,
    drop_pct FLOAT,
    poor_throws INT,
    poor_throws_pct FLOAT,
    sacked INT,
    blitzed INT,
    hurried INT,
    hits INT,
    pressured INT,
    pressured_pct FLOAT,
    scrmbl INT,
    yds_per_scrmbl FLOAT,
    PRIMARY KEY (player_id, week, season),
    FOREIGN KEY (player_id) REFERENCES player(player_id) ON DELETE CASCADE
);