# website URLs
website:
   pro-football-reference:
      urls:
         home-page: "https://www.pro-football-reference.com/"
         team-metrics: "https://www.pro-football-reference.com/teams/{TEAM_ACRONYM}/{CURRENT_YEAR}.htm"
         player-metrics: "https://www.pro-football-reference.com/players/{LAST_NAME_INITAL}/{HASHED_NAME}.htm"
   fantasy-pros:
      urls:
         depth-chart: "https://www.fantasypros.com/nfl/depth-chart/{TEAM}.php"
   rotowire:
      urls:
         historical-odds: "https://www.rotowire.com/betting/nfl/tables/games-archive.php"
         upcoming-odds: "https://www.rotowire.com/betting/nfl/tables/nfl-games-by-market.php?week={WEEK}"

# scraping
scraping:
   delay: 3

# scoring
scoring:
   offense:
      passing:
         yard: 0.04
         td: 4
         int: -2
         two_pt_conversion: 2
      rushing:
         yard: 0.1
         td: 6
         two_pt_conversion: 2
      receiving:
         yard: 0.1
         rec: 1
         td: 6
         two_pt_conversion: 2

rankings:
   weights:
      td: 0.6
      yards: 0.4

# NFL teams
nfl:
   current-year: 2024
   teams:
      - name: Arizona Cardinals
        acronym: crd
        pfr_acronym: ARI
      - name: Atlanta Falcons
        acronym: atl
        pfr_acronym: ATL
      - name: Baltimore Ravens
        acronym: rav
        pfr_acronym: BAL
      - name: Buffalo Bills
        acronym: buf
        pfr_acronym: BUF
      - name: Carolina Panthers
        acronym: car
        pfr_acronym: CAR
      - name: Chicago Bears
        acronym: chi
        pfr_acronym: CHI
      - name: Cincinnati Bengals
        acronym: cin
        pfr_acronym: CIN
      - name: Cleveland Browns
        acronym: cle
        pfr_acronym: CLE
      - name: Dallas Cowboys
        acronym: dal
        pfr_acronym: DAL
      - name: Denver Broncos
        acronym: den
        pfr_acronym: DEN
      - name: Detroit Lions
        acronym: det
        pfr_acronym: DET
      - name: Green Bay Packers
        acronym: gnb
        pfr_acronym: GNB
        rotowire: GB
      - name: Houston Texans
        acronym: htx
        pfr_acronym: HOU
      - name: Indianapolis Colts
        acronym: clt
        pfr_acronym: IND
      - name: Jacksonville Jaguars
        acronym: jax
        pfr_acronym: JAX
      - name: Kansas City Chiefs
        acronym: kan
        pfr_acronym: KAN
        rotowire: KC
      - name: Las Vegas Raiders
        acronym: rai
        pfr_acronym: LVR
        rotowire: LV
      - name: Los Angeles Chargers
        acronym: sdg
        pfr_acronym: LAC
      - name: Los Angeles Rams
        acronym: ram
        pfr_acronym: LAR
      - name: Miami Dolphins
        acronym: mia
        pfr_acronym: MIA
      - name: Minnesota Vikings
        acronym: min
        pfr_acronym: MIN
      - name: New England Patriots
        acronym: nwe
        pfr_acronym: NWE
        rotowire: NE
      - name: New Orleans Saints
        acronym: nor
        pfr_acronym: NOR
        rotowire: "NO"
      - name: New York Giants
        acronym: nyg
        pfr_acronym: NYG
      - name: New York Jets
        acronym: nyj
        pfr_acronym: NYJ
      - name: Philadelphia Eagles
        acronym: phi
        pfr_acronym: PHI
      - name: Pittsburgh Steelers
        acronym: pit
        pfr_acronym: PIT
      - name: San Francisco 49ers
        acronym: sfo
        pfr_acronym: SFO
        rotowire: SF
      - name: Seattle Seahawks
        acronym: sea
        pfr_acronym: SEA
      - name: Tampa Bay Buccaneers
        acronym: tam
        pfr_acronym: TAM
        rotowire: TB
      - name: Tennessee Titans
        acronym: oti
        pfr_acronym: TEN
      - name: Washington Commanders
        acronym: was
        pfr_acronym: WAS
