# website configurations
website:
   pro-football-reference:
      urls:
         home-page: "https://www.pro-football-reference.com/"
         team-metrics: "https://www.pro-football-reference.com/teams/{TEAM_ACRONYM}/{CURRENT_YEAR}.htm"
         player-metrics: "https://www.pro-football-reference.com/players/{LAST_NAME_INITAL}/{HASHED_NAME}.htm"
   fantasy-pros:
      urls:
         depth-chart: "https://www.fantasypros.com/nfl/depth-chart/{TEAM}.php"
   rotowire:
      urls:
         historical-odds: "https://www.rotowire.com/betting/nfl/tables/games-archive.php"
         upcoming-odds: "https://www.rotowire.com/betting/nfl/tables/nfl-games-by-market.php"
   betting-pros:
      market-ids: "73:74:102:103:100:333:101:106:107:76:105:75:104:66:71:78:253"
      api-key: "CHi8Hy5CEE4khd46XNYL23dCFX96oUdw6qOt1Dnh"
      urls:
         historical-odds: "https://api.bettingpros.com/v3/offers?sport=NFL&market_id={MARKET_IDS}&player_slug={PLAYER_SLUG}&event_id={EVENT_IDS}&location=NY&limit=5&page={PAGE}"
         events: "https://api.bettingpros.com/v3/events?sport=NFL&week={WEEK}&season={YEAR}"

# scraping
scraping:
   delay: 3

# weights for feature manipulation
weights:
   game_context:
      game_over_under: 0.40
      anytime_touchdown_scorer_line: 0.60
   fantasy_potential:
      log_avg_fantasy_points: 0.4
      fantasy_points_over_under_line: 0.6
   expected_rushing_volume:
      rushing_attempts_over_under_line: 0.2
      rushing_yards_over_under_line: 0.8
   expected_receiving_volume:
      receptions_over_under_line: 0.5
      receiving_yards_over_under_line: 0.5
   expected_passing_volume:
      passing_touchdowns_over_under_line: 0.5
      passing_attempts_over_under_line: 0.1
      passing_yards_over_under_line: 0.4
   total_expected_volume_rb:
      expected_receiving_volume: 0.4
      expected_rushing_volume: 0.6
   total_expected_volume_qb:
      expected_passing_volume: 0.88
      expected_rushing_volume: 0.12
      dual_threat_passing_volume: 0.68
      dual_thread_rushing_volume: 0.32
   qb_composite_score:
      total_expected_volume_qb: 0.5
      fantasy_potential: 0.3
      game_context: 0.2
   rb_composite_score:
      total_expected_volume_rb: 0.5
      fantasy_potential: 0.3
      game_context: 0.2
   wr_te_composite_score:
      expected_receiving_volume: 0.7
      fantasy_potential: 0.2
      game_context: 0.1

# scoring
scoring:
   offense:
      passing:
         yard: 0.04
         td: 4
         int: -2
         two_pt_conversion: 2
      rushing:
         yard: 0.1
         td: 6
         two_pt_conversion: 2
      receiving:
         yard: 0.1
         rec: 1
         td: 6
         two_pt_conversion: 2

rankings:
   weights:
      td: 0.6
      yards: 0.4

# NFL teams
nfl:
   current-year: 2024
   teams:
      - name: Arizona Cardinals
        acronym: crd
        pfr_acronym: ARI
        our_lads_acronym: ARZ
      - name: Atlanta Falcons
        acronym: atl
        pfr_acronym: ATL
      - name: Baltimore Ravens
        acronym: rav
        pfr_acronym: BAL
      - name: Buffalo Bills
        acronym: buf
        pfr_acronym: BUF
      - name: Carolina Panthers
        acronym: car
        pfr_acronym: CAR
      - name: Chicago Bears
        acronym: chi
        pfr_acronym: CHI
      - name: Cincinnati Bengals
        acronym: cin
        pfr_acronym: CIN
      - name: Cleveland Browns
        acronym: cle
        pfr_acronym: CLE
      - name: Dallas Cowboys
        acronym: dal
        pfr_acronym: DAL
      - name: Denver Broncos
        acronym: den
        pfr_acronym: DEN
      - name: Detroit Lions
        acronym: det
        pfr_acronym: DET
      - name: Green Bay Packers
        acronym: gnb
        pfr_acronym: GNB
        rotowire: GB
        our_lads_acronym: GB
      - name: Houston Texans
        acronym: htx
        pfr_acronym: HOU
      - name: Indianapolis Colts
        acronym: clt
        pfr_acronym: IND
      - name: Jacksonville Jaguars
        acronym: jax
        pfr_acronym: JAX
      - name: Kansas City Chiefs
        acronym: kan
        pfr_acronym: KAN
        rotowire: KC
        our_lads_acronym: KC
      - name: Las Vegas Raiders
        acronym: rai
        pfr_acronym: LVR
        rotowire: LV
        our_lads_acronym: LV
      - name: Los Angeles Chargers
        acronym: sdg
        pfr_acronym: LAC
      - name: Los Angeles Rams
        acronym: ram
        pfr_acronym: LAR
      - name: Miami Dolphins
        acronym: mia
        pfr_acronym: MIA
      - name: Minnesota Vikings
        acronym: min
        pfr_acronym: MIN
      - name: New England Patriots
        acronym: nwe
        pfr_acronym: NWE
        rotowire: NE
        our_lads_acronym: NE
      - name: New Orleans Saints
        acronym: nor
        pfr_acronym: NOR
        rotowire: "NO"
        our_lads_acronym: "NO"
      - name: New York Giants
        acronym: nyg
        pfr_acronym: NYG
      - name: New York Jets
        acronym: nyj
        pfr_acronym: NYJ
      - name: Philadelphia Eagles
        acronym: phi
        pfr_acronym: PHI
      - name: Pittsburgh Steelers
        acronym: pit
        pfr_acronym: PIT
      - name: San Francisco 49ers
        acronym: sfo
        pfr_acronym: SFO
        rotowire: SF
        our_lads_acronym: SF
      - name: Seattle Seahawks
        acronym: sea
        pfr_acronym: SEA
      - name: Tampa Bay Buccaneers
        acronym: tam
        pfr_acronym: TAM
        rotowire: TB
        our_lads_acronym: TB
      - name: Tennessee Titans
        acronym: oti
        pfr_acronym: TEN
      - name: Washington Commanders
        acronym: was
        pfr_acronym: WAS
