-- Store team game logs for a specific week/season 
CREATE TABLE team_game_log (
    team_id INT NOT NULL,
    week INT NOT NULL,
    day VARCHAR(20) NOT NULL,
    year INT NOT NULL,
    rest_days INT,
    home_team BOOLEAN,
    distance_traveled FLOAT,
    opp INT NOT NULL, -- opponent team_id
    result VARCHAR(20),
    points_for INT,
    points_allowed INT,
    tot_yds INT,
    pass_yds INT,
    rush_yds INT,
    opp_tot_yds INT,
    opp_pass_yds INT,
    opp_rush_yds INT,
    pass_tds INT,
    pass_cmp INT,
    pass_att INT,
    pass_cmp_pct FLOAT,
    rush_att INT,
    rush_tds INT,
    yds_gained_per_pass_att FLOAT,
    adj_yds_gained_per_pass_att FLOAT,
    pass_rate FLOAT,
    sacked INT,
    sack_yds_lost INT,
    rush_yds_per_att FLOAT,
    total_off_plays INT,
    total_yds INT,
    yds_per_play FLOAT,
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    total_punts INT,
    punt_yds INT,
    pass_fds INT,
    rsh_fds INT,
    pen_fds INT,
    total_fds INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    fourth_down_conv INT,
    fourth_down_att INT,
    penalties INT,
    penalty_yds INT,
    fmbl_lost INT,
    int INT,
    turnovers INT,
    time_of_poss FLOAT,
    game_date DATE,
    PRIMARY KEY (team_id, week, year),
    FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE,
    FOREIGN KEY (opp) REFERENCES team(team_id) ON DELETE CASCADE
);